### ISSUE TITLE
Lack of CmdletBinding prevents ErrorAction from propagating

### ISSUE THREAD

**Issue by tomrowton-alk** [microsoft/PowerShell-FeatureFlags#53]
It seems that not having `[CmdletBinding()]` for the functions is preventing an explicitly passed `-ErrorAction` from propagating to  child calls. For example, if I call `Get-FeatureFlagConfigFromFile -jsonConfigPath $f -ErrorAction SilentlyContinue` where `$f` is a path that does not exist, you will get a halting error; however, if I add `[CmdletBinding()]` to that function, the halting error moves to the child call `Confirm-FeatureFlagConfig` - and if I add `[CmdletBinding()]` to *that* function, then I get back `$null` like `Get-FeatureFlagConfigFromFile` code is written.

To reproduce: 
Call `$c = Get-FeatureFlagConfigFromFile -jsonConfigPath $f` where `$f` is a path that does not exist
then 
Call `$c2 = Get-FeatureFlagConfigFromFile -jsonConfigPath $f -ErrorAction SilentlyContinue` where `$f` is a path that does not exist

$c2 should be returned without outputting an error to the console, and be `$null`
I thought this was working in earlier tests, but trying it now, `-ErrorAction` is not being passed on.

I'm using version 2.1.0 of FeatureFlags in Powershell 5 with the following `$PSVersionTable`
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by lupino3** [comment]
Thanks for the bug report! We should indeed have `CmdletBinding()` calls.

I'll add those, and see if I can use your repro instructions as a unit test.
Thanks!

**Comment by lupino3** [comment]
Should be fixed. Thanks for the bug report! I'll try to do a release today.

**Comment by lupino3** [comment]
The fix is released in version 2.1.1: https://github.com/microsoft/PowerShell-FeatureFlags/releases/tag/2.1.1.

**Comment by tomrowton-alk** [comment]
Thank you very much!

**Comment by tomrowton-alk** [comment]
Verified working for me.
